import 'package:desayur/models/products_model.dart';

class Consts {
  static final List<String> offerImages = [
    'assets/images/offres/Offer1.jpg',
    'assets/images/offres/Offer2.jpg',
    'assets/images/offres/Offer3.jpg',
    'assets/images/offres/Offer4.jpg',
  ];

  static final List<String> authImagesPaths = [
    'assets/images/landing/buy-on-laptop.jpg',
    'assets/images/landing/buy-through.png',
    'assets/images/landing/buyfood.jpg',
    'assets/images/landing/grocery-cart.jpg',
    'assets/images/landing/vergtablebg.jpg',
    'assets/images/landing/store.jpg',
  ];

  static final List<ProductModel> productsList = [
    ProductModel(
      id: 'Apricots',
      title: 'Apricots',
      imageUrl: 'https://i.ibb.co/F0s3FHQ/Apricots.png',
      productCategoryName: 'Fruits',
      price: 0.99,
      salePrice: 0.35,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Green grape',
      title: 'Green Grape',
      imageUrl: 'https://i.ibb.co/bHKtc33/grape-green.png',
      productCategoryName: 'Fruits',
      price: 0.99,
      salePrice: 0.4,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Kangkong',
      title: 'Kangkong',
      imageUrl: 'https://i.ibb.co/HDSrR2Y/Kangkong.png',
      productCategoryName: 'Herbs',
      price: 0.99,
      salePrice: 0.5,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Leek',
      title: 'Leek',
      imageUrl: 'https://i.ibb.co/Pwhqkh6/Leek.png',
      productCategoryName: 'Herbs',
      price: 0.99,
      salePrice: 0.5,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Carottes',
      title: 'Carottes',
      imageUrl: 'https://i.ibb.co/TRbNL3c/Carottes.png',
      productCategoryName: 'Vegetables',
      price: 0.99,
      salePrice: 0.5,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Cauliflower',
      title: 'Cauliflower',
      imageUrl: 'https://i.ibb.co/xGWf2rH/Cauliflower.png',
      productCategoryName: 'Vegetables',
      price: 0.99,
      salePrice: 0.39,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Corn-cobs',
      title: 'Corn-cobs',
      imageUrl: 'https://i.ibb.co/8PhwVYZ/corn-cobs.png',
      productCategoryName: 'Grains',
      price: 0.99,
      salePrice: 0.35,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Peas',
      title: 'Peas',
      imageUrl: 'https://i.ibb.co/7GHM7Dp/peas.png',
      productCategoryName: 'Grains',
      price: 0.29,
      salePrice: 0.19,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Almond',
      title: 'Almond',
      imageUrl: 'https://i.ibb.co/c8QtSr2/almand.png',
      productCategoryName: 'Nuts',
      price: 0.29,
      salePrice: 0.19,
      isOnSale: false,
      isPiece: true,
    ),
    ProductModel(
      id: 'Chinese-cabbage-wombok',
      title: 'Chinese-cabbage-wombok',
      imageUrl: 'https://i.ibb.co/7yzjHVy/Chinese-cabbage-wombok.png',
      productCategoryName: 'Spices',
      price: 0.99,
      salePrice: 0.15,
      isOnSale: false,
      isPiece: true,
    ),
  ];
}
